// PLACEHOLDER — generated file substitute.
//
// In a real project this file is generated by the FlutterFire CLI:
//   dart pub global activate flutterfire_cli
//   flutterfire configure
//
// It intentionally contains NO real credentials. When running in demo mode
// (the default) Firebase is never initialised, so these placeholder values are
// never used. Replace this file by running `flutterfire configure` before
// enabling Firebase (USE_FIREBASE=true).
//
// This file is git-ignored by default (see .gitignore) once real values exist.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return _placeholder;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return _placeholder;
      case TargetPlatform.iOS:
        return _placeholder;
      default:
        return _placeholder;
    }
  }

  // These are obviously non-functional placeholders.
  static const FirebaseOptions _placeholder = FirebaseOptions(
    apiKey: 'REPLACE_WITH_FIREBASE_API_KEY',
    appId: 'REPLACE_WITH_APP_ID',
    messagingSenderId: 'REPLACE_WITH_SENDER_ID',
    projectId: 'REPLACE_WITH_PROJECT_ID',
    storageBucket: 'REPLACE_WITH_BUCKET',
  );
}
